### ISSUE TITLE
Moth Elytra doesn't use cape texture

### ISSUE THREAD

**Issue by IcewingCoder** [0vergrown/Moth-Origin#1]
I'm unsure if this is intended or not, but I just noticed the origin elytra for Moth doesn't use the cape texture like other origins.

**Comment by 0vergrown** [comment]
> I'm unsure if this is intended or not, but I just noticed the origin elytra for Moth doesn't use the cape texture like other origins.

The wing texture is being taken directly from Minecraft itself. Capes are not a feature that is supported by the Origins mod natively
